name: generate-snake-game

on:
  schedule:
    - cron: "0 0 * * *"  # runs every night
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write   # 👈 this line is important (fixes exit code 128)

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: karanjoshi-kj
          outputs: dist/snake.svg

      - name: Upload to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
